//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Forms;
using System.Windows.Ink;
using Color = System.Windows.Media.Color;
using FontFamily = System.Windows.Media.FontFamily;
using FontStyle = System.Windows.FontStyle;
using HorizontalAlignment = System.Windows.HorizontalAlignment;

namespace ScreenToGif.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool PreStart {
            get {
                return ((bool)(this["PreStart"]));
            }
            set {
                this["PreStart"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowCursor {
            get {
                return ((bool)(this["ShowCursor"]));
            }
            set {
                this["ShowCursor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Snapshot {
            get {
                return ((bool)(this["Snapshot"]));
            }
            set {
                this["Snapshot"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int StartUp {
            get {
                return ((int)(this["StartUp"]));
            }
            set {
                this["StartUp"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool MouseClicks {
            get {
                return ((bool)(this["MouseClicks"]));
            }
            set {
                this["MouseClicks"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UseDefaultOutput {
            get {
                return ((bool)(this["UseDefaultOutput"]));
            }
            set {
                this["UseDefaultOutput"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string DefaultOutput {
            get {
                return ((string)(this["DefaultOutput"]));
            }
            set {
                this["DefaultOutput"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("auto")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int LastFps {
            get {
                return ((int)(this["LastFps"]));
            }
            set {
                this["LastFps"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("518")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("269")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CustomEncoding {
            get {
                return ((bool)(this["CustomEncoding"]));
            }
            set {
                this["CustomEncoding"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF32CD32")]
        public Color TransparentColor {
            get {
                return ((Color)(this["TransparentColor"]));
            }
            set {
                this["TransparentColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool PaintTransparent {
            get {
                return ((bool)(this["PaintTransparent"]));
            }
            set {
                this["PaintTransparent"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Looped {
            get {
                return ((bool)(this["Looped"]));
            }
            set {
                this["Looped"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public int RepeatCount {
            get {
                return ((int)(this["RepeatCount"]));
            }
            set {
                this["RepeatCount"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool RepeatForever {
            get {
                return ((bool)(this["RepeatForever"]));
            }
            set {
                this["RepeatForever"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int Quality {
            get {
                return ((int)(this["Quality"]));
            }
            set {
                this["Quality"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F7")]
        public Keys StartPauseKey {
            get {
                return ((Keys)(this["StartPauseKey"]));
            }
            set {
                this["StartPauseKey"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F8")]
        public Keys StopKey {
            get {
                return ((Keys)(this["StopKey"]));
            }
            set {
                this["StopKey"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DetectUnchanged {
            get {
                return ((bool)(this["DetectUnchanged"]));
            }
            set {
                this["DetectUnchanged"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFF5F5F5")]
        public Color GridColor1 {
            get {
                return ((Color)(this["GridColor1"]));
            }
            set {
                this["GridColor1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFF0F0F0")]
        public Color GridColor2 {
            get {
                return ((Color)(this["GridColor2"]));
            }
            set {
                this["GridColor2"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0,0,20,20")]
        public Rect GridSize {
            get {
                return ((Rect)(this["GridSize"]));
            }
            set {
                this["GridSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FixedFrameRate {
            get {
                return ((bool)(this["FixedFrameRate"]));
            }
            set {
                this["FixedFrameRate"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1000")]
        public int SnapshotDefaultDelay {
            get {
                return ((int)(this["SnapshotDefaultDelay"]));
            }
            set {
                this["SnapshotDefaultDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int LastFpsImport {
            get {
                return ((int)(this["LastFpsImport"]));
            }
            set {
                this["LastFpsImport"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color InsertFillColor {
            get {
                return ((Color)(this["InsertFillColor"]));
            }
            set {
                this["InsertFillColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("SourceCopy")]
        public CopyPixelOperation CaptureMode {
            get {
                return ((CopyPixelOperation)(this["CaptureMode"]));
            }
            set {
                this["CaptureMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double EditorTop {
            get {
                return ((double)(this["EditorTop"]));
            }
            set {
                this["EditorTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double EditorLeft {
            get {
                return ((double)(this["EditorLeft"]));
            }
            set {
                this["EditorLeft"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double EditorHeight {
            get {
                return ((double)(this["EditorHeight"]));
            }
            set {
                this["EditorHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double EditorWidth {
            get {
                return ((double)(this["EditorWidth"]));
            }
            set {
                this["EditorWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public WindowState EditorWindowState {
            get {
                return ((WindowState)(this["EditorWindowState"]));
            }
            set {
                this["EditorWindowState"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Text")]
        public string CaptionText {
            get {
                return ((string)(this["CaptionText"]));
            }
            set {
                this["CaptionText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI")]
        public FontFamily CaptionFontFamily {
            get {
                return ((FontFamily)(this["CaptionFontFamily"]));
            }
            set {
                this["CaptionFontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FontStyle CaptionFontStyle {
            get {
                return ((FontStyle)(this["CaptionFontStyle"]));
            }
            set {
                this["CaptionFontStyle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Bold")]
        public FontWeight CaptionFontWeight {
            get {
                return ((FontWeight)(this["CaptionFontWeight"]));
            }
            set {
                this["CaptionFontWeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public double CaptionFontSize {
            get {
                return ((double)(this["CaptionFontSize"]));
            }
            set {
                this["CaptionFontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color CaptionFontColor {
            get {
                return ((Color)(this["CaptionFontColor"]));
            }
            set {
                this["CaptionFontColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double CaptionOutlineThickness {
            get {
                return ((double)(this["CaptionOutlineThickness"]));
            }
            set {
                this["CaptionOutlineThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color CaptionOutlineColor {
            get {
                return ((Color)(this["CaptionOutlineColor"]));
            }
            set {
                this["CaptionOutlineColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Bottom")]
        public VerticalAlignment CaptionVerticalAligment {
            get {
                return ((VerticalAlignment)(this["CaptionVerticalAligment"]));
            }
            set {
                this["CaptionVerticalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Center")]
        public HorizontalAlignment CaptionHorizontalAligment {
            get {
                return ((HorizontalAlignment)(this["CaptionHorizontalAligment"]));
            }
            set {
                this["CaptionHorizontalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double CaptionMargin {
            get {
                return ((double)(this["CaptionMargin"]));
            }
            set {
                this["CaptionMargin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Text")]
        public string FreeTextText {
            get {
                return ((string)(this["FreeTextText"]));
            }
            set {
                this["FreeTextText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI")]
        public FontFamily FreeTextFontFamily {
            get {
                return ((FontFamily)(this["FreeTextFontFamily"]));
            }
            set {
                this["FreeTextFontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FontStyle FreeTextFontStyle {
            get {
                return ((FontStyle)(this["FreeTextFontStyle"]));
            }
            set {
                this["FreeTextFontStyle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FontWeight FreeTextFontWeight {
            get {
                return ((FontWeight)(this["FreeTextFontWeight"]));
            }
            set {
                this["FreeTextFontWeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color FreeTextFontColor {
            get {
                return ((Color)(this["FreeTextFontColor"]));
            }
            set {
                this["FreeTextFontColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("14")]
        public double FreeTextFontSize {
            get {
                return ((double)(this["FreeTextFontSize"]));
            }
            set {
                this["FreeTextFontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("500")]
        public int NewImageWidth {
            get {
                return ((int)(this["NewImageWidth"]));
            }
            set {
                this["NewImageWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("200")]
        public int NewImageHeight {
            get {
                return ((int)(this["NewImageHeight"]));
            }
            set {
                this["NewImageHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color NewImageColor {
            get {
                return ((Color)(this["NewImageColor"]));
            }
            set {
                this["NewImageColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Title")]
        public string TitleFrameText {
            get {
                return ((string)(this["TitleFrameText"]));
            }
            set {
                this["TitleFrameText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI")]
        public FontFamily TitleFrameFontFamily {
            get {
                return ((FontFamily)(this["TitleFrameFontFamily"]));
            }
            set {
                this["TitleFrameFontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FontStyle TitleFrameFontStyle {
            get {
                return ((FontStyle)(this["TitleFrameFontStyle"]));
            }
            set {
                this["TitleFrameFontStyle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Normal")]
        public FontWeight TitleFrameFontWeight {
            get {
                return ((FontWeight)(this["TitleFrameFontWeight"]));
            }
            set {
                this["TitleFrameFontWeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color TitleFrameFontColor {
            get {
                return ((Color)(this["TitleFrameFontColor"]));
            }
            set {
                this["TitleFrameFontColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Center")]
        public VerticalAlignment TitleFrameVerticalAligment {
            get {
                return ((VerticalAlignment)(this["TitleFrameVerticalAligment"]));
            }
            set {
                this["TitleFrameVerticalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Center")]
        public HorizontalAlignment TitleFrameHorizontalAligment {
            get {
                return ((HorizontalAlignment)(this["TitleFrameHorizontalAligment"]));
            }
            set {
                this["TitleFrameHorizontalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFD7D7D7")]
        public Color TitleFrameBackgroundColor {
            get {
                return ((Color)(this["TitleFrameBackgroundColor"]));
            }
            set {
                this["TitleFrameBackgroundColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("20")]
        public double TitleFrameFontSize {
            get {
                return ((double)(this["TitleFrameFontSize"]));
            }
            set {
                this["TitleFrameFontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double TitleFrameMargin {
            get {
                return ((double)(this["TitleFrameMargin"]));
            }
            set {
                this["TitleFrameMargin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double RecorderTop {
            get {
                return ((double)(this["RecorderTop"]));
            }
            set {
                this["RecorderTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public double RecorderLeft {
            get {
                return ((double)(this["RecorderLeft"]));
            }
            set {
                this["RecorderLeft"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string WatermarkFilePath {
            get {
                return ((string)(this["WatermarkFilePath"]));
            }
            set {
                this["WatermarkFilePath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.7")]
        public double WatermarkOpacity {
            get {
                return ((double)(this["WatermarkOpacity"]));
            }
            set {
                this["WatermarkOpacity"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double WatermarkSize {
            get {
                return ((double)(this["WatermarkSize"]));
            }
            set {
                this["WatermarkSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Bottom")]
        public VerticalAlignment WatermarkVerticalAligment {
            get {
                return ((VerticalAlignment)(this["WatermarkVerticalAligment"]));
            }
            set {
                this["WatermarkVerticalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Right")]
        public HorizontalAlignment WatermarkHorizontalAligment {
            get {
                return ((HorizontalAlignment)(this["WatermarkHorizontalAligment"]));
            }
            set {
                this["WatermarkHorizontalAligment"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double WatermarkMargin {
            get {
                return ((double)(this["WatermarkMargin"]));
            }
            set {
                this["WatermarkMargin"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color BorderColor {
            get {
                return ((Color)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double BorderLeftThickness {
            get {
                return ((double)(this["BorderLeftThickness"]));
            }
            set {
                this["BorderLeftThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double BorderTopThickness {
            get {
                return ((double)(this["BorderTopThickness"]));
            }
            set {
                this["BorderTopThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double BorderRightThickness {
            get {
                return ((double)(this["BorderRightThickness"]));
            }
            set {
                this["BorderRightThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double BorderBottomThickness {
            get {
                return ((double)(this["BorderBottomThickness"]));
            }
            set {
                this["BorderBottomThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int FreeDrawingPenWidth {
            get {
                return ((int)(this["FreeDrawingPenWidth"]));
            }
            set {
                this["FreeDrawingPenWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int FreeDrawingPenHeight {
            get {
                return ((int)(this["FreeDrawingPenHeight"]));
            }
            set {
                this["FreeDrawingPenHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color FreeDrawingColor {
            get {
                return ((Color)(this["FreeDrawingColor"]));
            }
            set {
                this["FreeDrawingColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Ellipse")]
        public StylusTip FreeDrawingStylusTip {
            get {
                return ((StylusTip)(this["FreeDrawingStylusTip"]));
            }
            set {
                this["FreeDrawingStylusTip"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FreeDrawingIsHighlighter {
            get {
                return ((bool)(this["FreeDrawingIsHighlighter"]));
            }
            set {
                this["FreeDrawingIsHighlighter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FreeDrawingFitToCurve {
            get {
                return ((bool)(this["FreeDrawingFitToCurve"]));
            }
            set {
                this["FreeDrawingFitToCurve"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int FreeDrawingEraserWidth {
            get {
                return ((int)(this["FreeDrawingEraserWidth"]));
            }
            set {
                this["FreeDrawingEraserWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int FreeDrawingEraserHeight {
            get {
                return ((int)(this["FreeDrawingEraserHeight"]));
            }
            set {
                this["FreeDrawingEraserHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Rectangle")]
        public StylusTip FreeDrawingEraserStylusTip {
            get {
                return ((StylusTip)(this["FreeDrawingEraserStylusTip"]));
            }
            set {
                this["FreeDrawingEraserStylusTip"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool EditorExtendChrome {
            get {
                return ((bool)(this["EditorExtendChrome"]));
            }
            set {
                this["EditorExtendChrome"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("66")]
        public int PlaybackOverrideDelay {
            get {
                return ((int)(this["PlaybackOverrideDelay"]));
            }
            set {
                this["PlaybackOverrideDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int PlaybackChangeDelay {
            get {
                return ((int)(this["PlaybackChangeDelay"]));
            }
            set {
                this["PlaybackChangeDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CinemagraphPenWidth {
            get {
                return ((int)(this["CinemagraphPenWidth"]));
            }
            set {
                this["CinemagraphPenWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CinemagraphPenHeight {
            get {
                return ((int)(this["CinemagraphPenHeight"]));
            }
            set {
                this["CinemagraphPenHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Ellipse")]
        public StylusTip CinemagraphStylusTip {
            get {
                return ((StylusTip)(this["CinemagraphStylusTip"]));
            }
            set {
                this["CinemagraphStylusTip"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CinemagraphIsHighlighter {
            get {
                return ((bool)(this["CinemagraphIsHighlighter"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CinemagraphFitToCurve {
            get {
                return ((bool)(this["CinemagraphFitToCurve"]));
            }
            set {
                this["CinemagraphFitToCurve"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CinemagraphEraserWidth {
            get {
                return ((int)(this["CinemagraphEraserWidth"]));
            }
            set {
                this["CinemagraphEraserWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CinemagraphEraserHeight {
            get {
                return ((int)(this["CinemagraphEraserHeight"]));
            }
            set {
                this["CinemagraphEraserHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Rectangle")]
        public StylusTip CinemagraphEraserStylusTip {
            get {
                return ((StylusTip)(this["CinemagraphEraserStylusTip"]));
            }
            set {
                this["CinemagraphEraserStylusTip"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#2000FF10")]
        public Color CinemagraphColor {
            get {
                return ((Color)(this["CinemagraphColor"]));
            }
            set {
                this["CinemagraphColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFF00")]
        public Color ClickColor {
            get {
                return ((Color)(this["ClickColor"]));
            }
            set {
                this["ClickColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public int FadeFrameCount {
            get {
                return ((int)(this["FadeFrameCount"]));
            }
            set {
                this["FadeFrameCount"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("500")]
        public int TitleFrameDelay {
            get {
                return ((int)(this["TitleFrameDelay"]));
            }
            set {
                this["TitleFrameDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color BoardColor {
            get {
                return ((Color)(this["BoardColor"]));
            }
            set {
                this["BoardColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Ellipse")]
        public StylusTip BoardStylusTip {
            get {
                return ((StylusTip)(this["BoardStylusTip"]));
            }
            set {
                this["BoardStylusTip"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int BoardStylusWidth {
            get {
                return ((int)(this["BoardStylusWidth"]));
            }
            set {
                this["BoardStylusWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int BoardStylusHeight {
            get {
                return ((int)(this["BoardStylusHeight"]));
            }
            set {
                this["BoardStylusHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool BoardIsHighlighter {
            get {
                return ((bool)(this["BoardIsHighlighter"]));
            }
            set {
                this["BoardIsHighlighter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool BoardFitToCurve {
            get {
                return ((bool)(this["BoardFitToCurve"]));
            }
            set {
                this["BoardFitToCurve"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int BoardEraserWidth {
            get {
                return ((int)(this["BoardEraserWidth"]));
            }
            set {
                this["BoardEraserWidth"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int BoardEraserHeight {
            get {
                return ((int)(this["BoardEraserHeight"]));
            }
            set {
                this["BoardEraserHeight"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Rectangle")]
        public StylusTip BoardEraserStylusTip {
            get {
                return ((StylusTip)(this["BoardEraserStylusTip"]));
            }
            set {
                this["BoardEraserStylusTip"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color BoardGridColor1 {
            get {
                return ((Color)(this["BoardGridColor1"]));
            }
            set {
                this["BoardGridColor1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color BoardGridColor2 {
            get {
                return ((Color)(this["BoardGridColor2"]));
            }
            set {
                this["BoardGridColor2"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0,0,20,20")]
        public Rect BoardGridSize {
            get {
                return ((Rect)(this["BoardGridSize"]));
            }
            set {
                this["BoardGridSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color BoardGridBackground {
            get {
                return ((Color)(this["BoardGridBackground"]));
            }
            set {
                this["BoardGridBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool TransparentCorner {
            get {
                return ((bool)(this["TransparentCorner"]));
            }
            set {
                this["TransparentCorner"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-666")]
        public int WatermarkTop {
            get {
                return ((int)(this["WatermarkTop"]));
            }
            set {
                this["WatermarkTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-666")]
        public int WatermarkLeft {
            get {
                return ((int)(this["WatermarkLeft"]));
            }
            set {
                this["WatermarkLeft"] = value;
            }
        }
    }
}
